cors:
  originPatterns: ${CORS_ORIGIN_PATTERNS}
security:
  jwt:
    token:
      secret-key: ${SECURITY_JWT_TOKEN_SECRET_KEY}
      expire-length: ${SECURITY_JWT_TOKEN_EXPIRE_LENGTH}

spring:
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      show-sql: false

springdoc:
  pathsToMatch:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true
